// contactsSlice.ts

// Import necessary functions and types from Redux Toolkit
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the structure of a contact
interface Contact {
  id: number;
  firstName: string;
  lastName: string;
  status: boolean;
}

// Define the structure of the state that holds contacts
interface ContactsState {
  contacts: Contact[];
}

// Define the initial state of the contacts slice
const initialState: ContactsState = {
  contacts: [
    {
      id: 42847,
      firstName: "Ajay",
      lastName: "Sharma",
      status: true,
    },
    {
      id: 6124,
      firstName: "Mani",
      lastName: "Shankar",
      status: false,
    },
  ],
};

// Create a slice using createSlice from Redux Toolkit
const contactsSlice = createSlice({
  name: "contacts", // Name of the slice
  initialState, // Initial state of the slice
  reducers: {
    // Reducer for adding a contact
    addContact: (state, action: PayloadAction<Contact>) => {
      state.contacts.push(action.payload); // Add the new contact to the contacts array
    },
    // Reducer for updating a contact
    updateContact: (state, action: PayloadAction<Contact>) => {
      const { id } = action.payload;
      // Find the index of the contact to update
      const index = state.contacts.findIndex((contact) => contact.id === id);
      if (index !== -1) {
        state.contacts[index] = action.payload; // Update the contact
      }
    },
    // Reducer for deleting a contact
    deleteContact: (state, action: PayloadAction<number>) => {
      // Filter out the contact with the specified ID
      state.contacts = state.contacts.filter(
        (contact) => contact.id !== action.payload
      );
    },
  },
});

// Export the action creators generated by the createSlice function
export const { addContact, updateContact, deleteContact } =
  contactsSlice.actions;

// Export the reducer generated by the createSlice function
export default contactsSlice.reducer;
